# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  user_password: '12345678'
  secret_key_base: d302d93c108e411ee14cb136d466dfcbee97df4c89f2ecdc891d351b87d3c8d71c41566b01d14ec00e0fe08bd92c70d5ef192a286f81f4d4f822d2035e20c201

test:
  user_password: '12345678'
  secret_key_base: 03f559c51b5100916649a0955e684c2c165870eecb7ef8208fa376ee396e0c421122d9219abc6acda2dbbed4da2dcea5e44e56c2ba1a6648abb2e551c708c819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  user_password: '12345678'
  secret_key_base: 03f559c51b5100916649a0955e684c2c165870eecb7ef8208fa376ee396e0c421122d9219abc6acda2dbbed4da2dcea5e44e56c2ba1a6648abb2e551c708c819
